distilabel:
  version: 1.5.3
pipeline:
  name: speech_embedding_pipeline
  description: null
  steps:
  - step:
      name: from_db_0
      resources:
        replicas: 1
        cpus: null
        gpus: null
        memory: null
        resources: null
      input_mappings: {}
      output_mappings: {}
      use_cache: true
      batch_size: 50
      dbPath: ./db/axiom.db
      sql: "\n            SELECT speech_id, speech, summary\n            FROM speeches\
        \ s\n        "
      runtime_parameters_info:
      - name: resources
        runtime_parameters_info:
        - name: replicas
          optional: true
          description: The number of replicas for the step.
        - name: cpus
          optional: true
          description: The number of CPUs assigned to each step replica.
        - name: gpus
          optional: true
          description: The number of GPUs assigned to each step replica.
        - name: memory
          optional: true
          description: The memory in bytes required for each step replica.
        - name: resources
          optional: true
          description: A dictionary containing names of custom resources and the number
            of those resources required for each step replica.
      - name: batch_size
        optional: true
        description: The number of rows that will contain the batches generated by
          the step.
      type_info:
        module: custom_modules.utils
        name: FromDb
    name: from_db_0
  - step:
      name: qwen3_embedder_0
      resources:
        replicas: 1
        cpus: null
        gpus: null
        memory: null
        resources: null
      input_mappings:
        text_to_embed: speech
      output_mappings:
        embedding: speech_embedding
      use_cache: true
      input_batch_size: 50
      model: Qwen/Qwen3-Embedding-8B
      max_length: 8192
      batch_size: 10
      runtime_parameters_info:
      - name: resources
        runtime_parameters_info:
        - name: replicas
          optional: true
          description: The number of replicas for the step.
        - name: cpus
          optional: true
          description: The number of CPUs assigned to each step replica.
        - name: gpus
          optional: true
          description: The number of GPUs assigned to each step replica.
        - name: memory
          optional: true
          description: The memory in bytes required for each step replica.
        - name: resources
          optional: true
          description: A dictionary containing names of custom resources and the number
            of those resources required for each step replica.
      - name: input_batch_size
        optional: true
        description: The number of rows that will contain the batches processed by
          the step.
      - name: model
        optional: true
      - name: max_length
        optional: true
      - name: batch_size
        optional: true
      type_info:
        module: custom_modules.CustomLLMs
        name: Qwen3Embedder
    name: qwen3_embedder_0
  - step:
      name: qwen3_embedder_1
      resources:
        replicas: 1
        cpus: null
        gpus: null
        memory: null
        resources: null
      input_mappings:
        text_to_embed: summary
      output_mappings:
        embedding: summary_embedding
      use_cache: true
      input_batch_size: 50
      model: Qwen/Qwen3-Embedding-8B
      max_length: 8192
      batch_size: 10
      runtime_parameters_info:
      - name: resources
        runtime_parameters_info:
        - name: replicas
          optional: true
          description: The number of replicas for the step.
        - name: cpus
          optional: true
          description: The number of CPUs assigned to each step replica.
        - name: gpus
          optional: true
          description: The number of GPUs assigned to each step replica.
        - name: memory
          optional: true
          description: The memory in bytes required for each step replica.
        - name: resources
          optional: true
          description: A dictionary containing names of custom resources and the number
            of those resources required for each step replica.
      - name: input_batch_size
        optional: true
        description: The number of rows that will contain the batches processed by
          the step.
      - name: model
        optional: true
      - name: max_length
        optional: true
      - name: batch_size
        optional: true
      type_info:
        module: custom_modules.CustomLLMs
        name: Qwen3Embedder
    name: qwen3_embedder_1
  - step:
      name: keep_columns_0
      resources:
        replicas: 1
        cpus: null
        gpus: null
        memory: null
        resources: null
      input_mappings: {}
      output_mappings: {}
      use_cache: true
      input_batch_size: 50
      columns:
      - speech_id
      - speech_embedding
      - summary_embedding
      runtime_parameters_info:
      - name: resources
        runtime_parameters_info:
        - name: replicas
          optional: true
          description: The number of replicas for the step.
        - name: cpus
          optional: true
          description: The number of CPUs assigned to each step replica.
        - name: gpus
          optional: true
          description: The number of GPUs assigned to each step replica.
        - name: memory
          optional: true
          description: The memory in bytes required for each step replica.
        - name: resources
          optional: true
          description: A dictionary containing names of custom resources and the number
            of those resources required for each step replica.
      - name: input_batch_size
        optional: true
        description: The number of rows that will contain the batches processed by
          the step.
      type_info:
        module: distilabel.steps.columns.keep
        name: KeepColumns
    name: keep_columns_0
  - step:
      name: to_json_file_0
      resources:
        replicas: 1
        cpus: null
        gpus: null
        memory: null
        resources: null
      input_mappings: {}
      output_mappings: {}
      use_cache: true
      input_batch_size: 50
      filename: speech-embeddings
      filepath: db/cache
      jsonl: true
      runtime_parameters_info:
      - name: resources
        runtime_parameters_info:
        - name: replicas
          optional: true
          description: The number of replicas for the step.
        - name: cpus
          optional: true
          description: The number of CPUs assigned to each step replica.
        - name: gpus
          optional: true
          description: The number of GPUs assigned to each step replica.
        - name: memory
          optional: true
          description: The memory in bytes required for each step replica.
        - name: resources
          optional: true
          description: A dictionary containing names of custom resources and the number
            of those resources required for each step replica.
      - name: input_batch_size
        optional: true
        description: The number of rows that will contain the batches processed by
          the step.
      type_info:
        module: custom_modules.utils
        name: ToJsonFile
    name: to_json_file_0
  connections:
  - from: from_db_0
    to:
    - qwen3_embedder_0
  - from: qwen3_embedder_0
    to:
    - qwen3_embedder_1
  - from: qwen3_embedder_1
    to:
    - keep_columns_0
  - from: keep_columns_0
    to:
    - to_json_file_0
  - from: to_json_file_0
    to: []
  routing_batch_functions: []
  type_info:
    module: distilabel.pipeline.local
    name: Pipeline
requirements: []
